# Generated by Django 4.1.6 on 2023-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='delete_status',
            new_name='receiver_delete_status',
        ),
        migrations.AddField(
            model_name='messages',
            name='sender_delete_status',
            field=models.BooleanField(default=False),
        ),
    ]
